os: linux
sudo: required
language: cpp
services:
- docker

before install:
- docker pull shesta/testtravis
- docker run -d -p 127.0.0.1:80:4567 shesta/testtravis /bin/sh -c "cd /root/testtravis/scripts; checks.sh start;"
- docker ps -a
- docker run shesta/testtravis /bin/sh -c "cd /root/testtravis/scripts; checks.sh start"

jobs:
  include:
  -name: "test"
   script:
   - checks.sh
  - name: "checks"
    script:
    - ShestA/TestTravis ./scripts/checks.sh
    - docker run -v `pwd`:`pwd` -w `pwd` --cap-add=SYS_PTRACE -t ./scripts/checks.sh
  - name: "tests"
    script:
    - docker run -v `pwd`:`pwd` -w `pwd` -t ./scripts/tests.sh
  - name: "quality"
    script:
    - ./scripts/genenv.sh
    - docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t ./scripts/coverage.sh
    # The bot has gone...
    # - docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/duplication.sh

notifications:
    email: false
